name: Chrome for Testing
on: push

jobs:
  chrome:
    runs-on: ubuntu-24.04
    name: E2E on Chrome for Testing
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v2
        with:
          chrome-version: 140  # Versão específica do Chrome for Testing
      
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          command: npm run test:cloud
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
