name: Opera
on: push
jobs:
  firefox:
    runs-on: ubuntu-24.04
    name: E2E on Opera
    steps:
      - uses: actions/checkout@v5
        with:
          browser: opera
      - uses: cypress-io/github-action@v6
        with:
          browser: opera
      - uses: cypress-io/github-action@v6.1.0
        with:
          browser: opera